name: step_create_python_environment
inputs:
  pythonVersion:
    required: false
    default: "3.9"
    type: string
runs:
  using: composite
  steps:
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.pythonVersion }}
  - run: |
      python -m pip install --upgrade pip
    shell: pwsh
