name: step_create_python_environment
inputs:
  pipFilePath:
    required: false
    default: "src/promptflow/dev_requirements.txt"
    type: string
  pythonVersion:
    required: false
    default: "3.9"
    type: string
runs:
  using: composite
  steps:
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.pythonVersion }}
  - run: |
      python -m pip install --upgrade pip
      pip install -r ${{ inputs.pipFilePath }}
      pip freeze
      $python_env_path = (python -c 'import os, sys; print(os.path.dirname(sys.executable))')
      echo "Python environment path: $python_env_path"
      echo $python_env_path > ${{ github.workspace }}/python_env_path.txt
    shell: pwsh
