apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-classification-serve-app
spec:
  selector:
    matchLabels:
      app: web-classification-serve-app
  replicas: 1
  template:
    metadata:
      labels:
        app: web-classification-serve-app
    spec:
      containers:
      - name: web-classification-serve-container
        image: <your-docker-hub-id>/web-classification-serve-update
        ports:
        - containerPort: <container_port>