name: pipelines_templates_steps_template_generate_configs
inputs:
  generateConnections:
    required: false
    default: true
    type: boolean
  generateEndpointConfig:
    required: false
    default: false
    type: boolean
  aoaiApiKey:
    required: false
    type: string
  aoaiApiEndpoint:
    required: false
    type: string
  bingApiKey:
    required: false
    type: string
  openaiApiKey:
    required: false
    type: string
  serpApiKey:
    required: false
    type: string
  contentSafetyApiKey:
    required: false
    type: string
  targetFolder:
    required: false
    default: "."
    type: string
runs:
  using: composite
  steps:
  - name: Generate the connections config file
    if: parameters['generateConnections'] == true
    run: |-
      set -e
      exit_code=0
      echo "Generating connection config file..."
      python3 ./scripts/generate_connection_config.py \
          --bing-key ${{ inputs.bingApiKey }} \
          --aoai-key ${{ inputs.aoaiApiKey }} \
          --aoai-endpoint ${{ inputs.aoaiApiEndpoint }} \
          --openai-key ${{ inputs.openaiApiKey }} \
          --serpapi-key ${{ inputs.serpApiKey }} \
          --content-safety-key ${{ inputs.contentSafetyApiKey }} \
          --folder-path ${{ inputs.targetFolder }}
      if [ -f "${{ inputs.targetFolder }}/connections.json" ]
      then
          echo "Config file generated."
          exit 0
      else
          echo "Failed to generate the connection file, please check your script and parameters."
          exit 1
      fi
    shell: bash
  - name: Generate the endpoint config file
    if: parameters['generateEndpointConfig'] == true
    run: |-
      set -e
      exit_code=0
      echo "Generating endpoint config file..."
      target_folder="${{ env.promptflowRepoLocation }}/src/promptflow-sdk"
      python3 ./scripts/generate_endpoint_config.py \
          --url $(ENDPOINT-URL) \
          --key $(ENDPOINT-KEY) \
          --folder-path ${{ inputs.targetFolder }}
      if [ -f "${{ inputs.targetFolder }}/endpoint_config.json" ]
      then
          echo "Config file generated."
          exit 0
      else
          echo "Failed to generate the endpoint file, please check your script and parameters."
          exit 1
      fi
    shell: bash