$schema: https://azuremlschemas.azureedge.net/promptflow/latest/OrchestrationRun.schema.json

data: data.jsonl

jobs:
#  - type: script
#    name: gen_data
#    source:
#      type: code
#      path: generate_data.py
#    inputs:
#      site_list_file: site_list.jsonl  # File path as input

# flows
  - type: flow
    name: main
    flow: ../flows/standard/web-classification/flow.dag.yaml
    column_mapping:
      url: ${data.url}
    variant: ${summarize_text_content.variant_0}
  - type: flow
    name: eval1
    flow: ../flows/evaluation/eval-classification-accuracy-new1
    column_mapping:
      groundtruth: ${gen_data.outputs.answer}
      prediction: ${main.outputs.category}
# aggregations
  - type: script
    name: accuracy1
    source:
      type: code
      path: calculate_accuracy.py
    inputs:
      grades: ${eval1.outputs.grade}  # Aggregated list of flow output lines
