name: pipelines_templates_steps_template_initialize_build_step
inputs:
  condaEnvironmentFilePath:
    required: false
    default: "scripts/building/release-env.yml"
    type: string
runs:
  using: composite
  steps:
  - uses: "./.github/actions/pipelines_templates_steps_template_display_environment_variables_step"
  - uses: "./.github/actions/pipelines_templates_steps_template_create_conda_environment_step"
    with:
      condaEnvironmentFilePath: ${{ inputs.condaEnvironmentFilePath }}