name: pipelines_templates_steps_template_create_conda_environment_step
inputs:
  condaEnvironmentFilePath:
    required: false
    default: "./pipelines/configs/release-env.yaml"
    type: string
  condaEnvironmentName:
    required: false
    default: "$(Build.BuildId)"
    type: string
runs:
  using: composite
  steps:
  - name: Setup Miniconda
    uses: conda-incubator/setup-miniconda@v2
    with:
      activate-environment: release-env
      environment-file: scripts/building/release-env.yml
      python-version: 3.9
      condarc-file: scripts/building/example-condarc.yml
      auto-activate-base: false
  - name: Test conda environment
    run: |
      conda list
    shell: bash