name: check_enforcer

on:
  pull_request:
    branches: [ main ]

jobs:
  check_enforcer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch origin main
      - run: env | sort >> $GITHUB_OUTPUT
      - name: Summarize check status
        id: summarize_check_status
        working-directory: ${{ github.workspace }}
        shell: pwsh
        run: |
            . .\scripts\building\check_enforcer.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
