name: Create promptflow release branch

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Release version
        required: true

jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create branch
        run: |
          set -x -e

          release_branch_name="release/promptflow/${{ github.event.inputs.release_version }}"
          git checkout -b $release_branch_name

          echo "Replacing version in src/promptflow/promptflow/_version.py..."
          sed -i "s/0.0.1/${{ github.event.inputs.release_version }}/g" src/promptflow/promptflow/_version.py
          echo "Replaced src/promptflow/promptflow/_version.py:"
          cat src/promptflow/promptflow/_version.py

          git add src/promptflow/promptflow/_version.py
          git commit -m "Create release branch for version ${{ github.event.inputs.release_version }}"
          git push --set-upstream origin ${{ github.event.inputs.release_version }}
