name: examples_flowdag_schema_check

on:
  pull_request:
    paths:
      - examples/**
      - .github/workflows/flowdag_schema_check.yml
jobs:
  examples_flowdag_schema_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: env | sort >> $GITHUB_OUTPUT
      - name: Python Setup - ubuntu-latest - Python Version 3.9
        uses: "./.github/actions/step_create_python_environment"
        with:
          pythonVersion: 3.9
      - run: pip install -r ${{ github.workspace }}/examples/dev_requirements.txt
      - name: Summarize check status
        id: summarize_check_status
        working-directory: ${{ github.workspace }}
        shell: pwsh
        env:
          PYTHONPATH: ${{ github.workspace }}/src/promptflow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ github.workspace }}/src/promptflow
          pip install -e .
          python ${{ github.workspace }}/scripts/readme/schema_checker.py
