# This is a basic workflow that is for execute examples

name: Manual workflow
on:
  pull_request:
    branches: [ main,preview/code-first ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        client-id: "4cbd0e2e-aae4-4099-b4ba-94d3a4910587"
        tenant-id: "72f988bf-86f1-41af-91ab-2d7cd011db47"
        enable-AzPSSession: true
