# This is a basic workflow that is for execute examples

name: Manual workflow
on:
  pull_request:
    branches: [ main,preview/code-first ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate config.json
        run: |
          echo "{\"subscription_id\": \"96aede12-2f73-41cb-b983-6d11a904839b\",\"resource_group\": \"promptflow\",\"workspace_name\": \"promptflow-eastus\"}" > ${{ github.workspace }}/examples/config.json
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Python 3.9 environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Prepare requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/examples/requirements.txt
          pip install -r ${{ github.workspace }}/examples/dev-requirements.txt
      - name: Test connection
        run: pf connection list
      - name: Generate Configs
        uses: "./.github/actions/template_generate_configs"
        with:
          generateConnections: true
          generateEndpointConfig: false
          aoaiApiKey: ${{ secrets.AOAI_API_KEY }}
          aoaiApiEndpoint: ${{ secrets.AOAI_API_ENDPOINT }}
          bingApiKey: ${{ secrets.BING_API_KEY }}
          openaiApiKey: ${{ secrets.OPENAI_API_KEY }}
          serpApiKey: ""
          contentSafetyApiKey: ""
          targetFolder: ${{ github.workspace }}/scripts
      - name: Test Connection again
        run: pf connection list
      - name: Test Config Notebook
        run: |
          papermill -k python configuration.ipynb -
        working-directory: examples
      - name: Test Notebook
        run: |
          papermill -k python quickstart.ipynb quickstart.output.ipynb
        working-directory: examples/tutorials/get-started
      - name: upload notebook's working folder as an artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: quickstart
          path: examples/tutorials/get-started
