name: Publish Promptflow Doc

on:
  workflow_dispatch:
  push: 
    branches:
      - main
    paths:
      - 'README.md'
      - 'docs/**'
      - 'scripts/doc/**'
      - '.github/workflows/publish_doc.yml'

jobs:
  build_and_deploy_job:
    runs-on: windows-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build Doc
        shell: powershell
        working-directory: scripts/doc/
        run: ./doc_generation.ps1
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZ_CREDS}}
          enable-AzPSSession: true 

      - name: Deploy
        run: az webapp up --location eastus --name promptflow -g ${{secrets.DOC_RESOURCE_GROUP}} --subscription ${{secrets.DOC_SUBSCRIPTION_ID}} --html
        working-directory: scripts/doc/_build
