# Environment variables defined in a calling workflow are not accessible to this reusable workflow.
# Inputs are limit to 10.
name: template_run_tests
on:
  workflow_dispatch:
    inputs:
      pytestMarker:
        required: false
        type: string
      packageSetupType:
        required: false
        type: string
      testWorkingDirectory:
        required: false
        type: string
      location:
        required: false
        type: string
      coveragePath:
        required: false
        type: string
      coverage:
        required: false
        default: true
        type: boolean
      testPath:
        required: false
        type: string
      modelFileName:
        required: false
        default: ''
        type: string
jobs:
  run_feature_tests:
    name: Run Coverage Tests
    runs-on: ubuntu-latest
    timeout-minutes: ${{ parameters.timeoutInMinutes }}
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/steps_template_initialize_build_step"
      with:
        shouldEnableAutoCRLF: true
        shouldRunCheckout: true
        shouldCreateCondaEnvironment: false
        condaEnvironmentFilePath: "./pipelines/configs/release-env.yaml"
    - uses: "./.github/actions/steps_template_generate_configs"
      with:
        generateEndpointConfig: "false"
        aoaiApiKey: "${{ secrets.AOAI-API-KEY }}"
        aoaiApiEndpoint: "$(AOAI-API-ENDPOINT)"
        bingApiKey: "${{ secrets.BING-API-KEY }}"
        openaiApiKey: "${{ secrets.OPENAI-API-KEY }}"
        serpApiKey: "${{ secrets.SERPAPI-API-KEY }}"
        contentSafetyApiKey: "${{ secrets.CONTENT-SAFETY-API-KEY }}"
        targetFolder: "${{ env.srcPath }}/promptflow"
    - uses: "./.github/actions/steps_template_sdk_setup_step"
      with:
        setupType: "${{ inputs.packageSetupType }}"
    - uses: "./.github/actions/steps_template_test_coverage_step"
      with:
        workingDir: "${{ inputs.testWorkingDirectory }}"
        coveragePath: "${{ inputs.coveragePath }}"
        testPath: "${{ inputs.testPath }}"
        numPytestProcesses: "${{ inputs.numPytestProcesses }}"
        coverage: "${{ inputs.coverage }}"
        location: "${{ inputs.location }}"
        pytestMarker: "${{ inputs.pytestMarker }}"
        modelFileName: "${{ inputs.modelFileName }}"
