name: tools_continuous_delivery

on:
  push:
    branches:
      - main
    paths:
      - 'src/promptflow-tools/**'
      - '!README.*'
      - '!src/promptflow-tools/tests/**'

  workflow_dispatch:
    inputs:
      UploadAsLatest:
        description: 'True to upload the distribution as latest'
        required: true
        default: "False"
        type: choice
        options:
          - "True"
          - "False"
      SourceFolderName:
        description: 'The source folder of the distribution'
        required: true
        default: "promptflow-tools"
        type: string

jobs:
  manual_release:
    needs: approve_manual_release
    uses: ./.github/workflows/wheel_distributing.yml
    name: Manual release
    with:
      ReleaseType: "Test"
      UploadAsLatest: ${{ inputs.UploadAsLatest }}
      SourceFolderName: ${{ inputs.SourceFolderName }}
      ConfigsFolderPath: "scripts/distributing/configs"
    secrets: inherit

  continuous_delivery_release:
    if: github.event_name == 'push'
    uses: ./.github/workflows/wheel_distributing.yml
    name: Continuous delivery release
    with:
      ReleaseType: "Test"
      UploadAsLatest: "True"
      SourceFolderName: "promptflow-tools"
      ConfigsFolderPath: "scripts/distributing/configs"
    secrets: inherit

  deploy_runtime_with_updated_tools_package:
    needs: continuous_delivery_release
    uses: ./.github/workflows/tools_deploy_runtime.yml
    name: Deploy runtime
    with:
      ToolsPackageVersion: ${{ needs.continuous_delivery_release.outputs.PackageVersion }}
    secrets: inherit
