name: Promptflow Tools Pre Manual Release

on:
  pull_request:

  workflow_dispatch:
    inputs:
      ReleaseType:
        description: 'manual test'
        required: true
        default: "Test"
        type: string
      SourceFolderName:
        description: 'The source folder of the distribution'
        required: true
        default: "promptflow-tools"
        type: string

jobs:
  manual_release:
    uses: ./.github/workflows/wheel_distributing.yml
    name: Manual release
    with:
      ReleaseType: "Test"
      UploadAsLatest: "False"
      SourceFolderName: "promptflow-tools"
      ConfigsFolderPath: "scripts/distributing/configs"
    secrets: inherit
  
  get_timestamp:
    needs: manual_release
    name: Get Timestamp
    runs-on: ubuntu-latest

    steps:
    - name: Get Timestamp
      id: timestamp_step
      run: echo "::set-output name=version::0.0.$(date +%s)"

  deploy_runtime_with_updated_tools_package:
    needs: get_timestamp
    name: Deploy runtime
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Runtime
      uses: ./.github/workflows/deploy_runtime.yml
      with:
        ToolsPackageVersion: "${{ needs.get_timestamp.outputs.version }}"
