name: tools_continuous_delivery

on:
  push:
    branches:
      - main
    paths:
      - 'src/promptflow-tools/**'
      - '!README.*'
      - '!src/promptflow-tools/tests/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
        type: string

jobs:
  continuous_delivery_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up for Release
        if: github.event_name == 'push'
        run: |
          echo "ReleaseType=Release" >> $GITHUB_ENV
          echo "UploadAsLatest=True" >> $GITHUB_ENV

      - name: Set up for Test
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "ReleaseType=Test" >> $GITHUB_ENV
          echo "UploadAsLatest=False" >> $GITHUB_ENV

      - name: Build and publish wheel distribution
        uses: ./.github/workflows/wheel_distributing.yml
        with:
          ReleaseType: ${{ env.ReleaseType }}
          UploadAsLatest: ${{ env.UploadAsLatest }}
          SourceFolderName: "promptflow-tools"
          ConfigsFolderPath: "scripts/distributing/configs"
